real-world:
  Ankylosaurus_&_Stegosaurus: EPFL/colormat/Ankylosaurus_&_Stegosaurus.mat
  Backlight_1: EPFL/colormat/Backlight_1.mat
  Backlight_2: EPFL/colormat/Backlight_2.mat
  Bikes: EPFL/colormat/Bikes.mat
  Black_Fence: EPFL/colormat/Black_Fence.mat
  Books: EPFL/colormat/Books.mat
  Bridge: EPFL/colormat/Bridge.mat
  Bush: EPFL/colormat/Bush.mat
  Chain-link_Fence_2: EPFL/colormat/Chain-link_Fence_2.mat
  Color_Chart_2: EPFL/colormat/Color_Chart_2.mat
  Color_Chart_3: EPFL/colormat/Color_Chart_3.mat
  Concrete_Cubes: EPFL/colormat/Concrete_Cubes.mat
  Danger_de_Mort: EPFL/colormat/Danger_de_Mort.mat
  Desktop: EPFL/colormat/Desktop.mat
  Diplodocus: EPFL/colormat/Diplodocus.mat
  Fountain_&_Bench: EPFL/colormat/Fountain_&_Bench.mat
  Fountain_&_Vincent_1: EPFL/colormat/Fountain_&_Vincent_1.mat
  Fountain_1: EPFL/colormat/Fountain_1.mat
  Fountain_2: EPFL/colormat/Fountain_2.mat
  Friends_2: EPFL/colormat/Friends_2.mat
  Game_Board: EPFL/colormat/Game_Board.mat
  Houses_&_Lake: EPFL/colormat/Houses_&_Lake.mat
  ISO_Chart_1: EPFL/colormat/ISO_Chart_1.mat
  ISO_Chart_10: EPFL/colormat/ISO_Chart_10.mat
  ISO_Chart_11: EPFL/colormat/ISO_Chart_11.mat
  ISO_Chart_13: EPFL/colormat/ISO_Chart_13.mat
  ISO_Chart_14: EPFL/colormat/ISO_Chart_14.mat
  ISO_Chart_16: EPFL/colormat/ISO_Chart_16.mat
  ISO_Chart_17: EPFL/colormat/ISO_Chart_17.mat
  ISO_Chart_19: EPFL/colormat/ISO_Chart_19.mat
  ISO_Chart_2: EPFL/colormat/ISO_Chart_2.mat
  ISO_Chart_22: EPFL/colormat/ISO_Chart_22.mat
  ISO_Chart_23: EPFL/colormat/ISO_Chart_23.mat
  ISO_Chart_4: EPFL/colormat/ISO_Chart_4.mat
  ISO_Chart_5: EPFL/colormat/ISO_Chart_5.mat
  ISO_Chart_8: EPFL/colormat/ISO_Chart_8.mat
  ISO_Chart_9: EPFL/colormat/ISO_Chart_9.mat
  Overexposed_Sky: EPFL/colormat/Overexposed_Sky.mat
  Palais_du_Luxembourg: EPFL/colormat/Palais_du_Luxembourg.mat
  Parc_du_Luxembourg: EPFL/colormat/Parc_du_Luxembourg.mat
  Perforated_Metal_1: EPFL/colormat/Perforated_Metal_1.mat
  Perforated_Metal_2: EPFL/colormat/Perforated_Metal_2.mat
  Perforated_Metal_3: EPFL/colormat/Perforated_Metal_3.mat
  Pond_in_Paris: EPFL/colormat/Pond_in_Paris.mat
  Poppies: EPFL/colormat/Poppies.mat
  Railway_Lines_1: EPFL/colormat/Railway_Lines_1.mat
  Red_&_White_Building: EPFL/colormat/Red_&_White_Building.mat
  Reeds: EPFL/colormat/Reeds.mat
  Rusty_Handle: EPFL/colormat/Rusty_Handle.mat
  Semi-reflecting_Structure_2: EPFL/colormat/Semi-reflecting_Structure_2.mat
  Slab_&_Lake: EPFL/colormat/Slab_&_Lake.mat
  Sophie_&_Vincent_1: EPFL/colormat/Sophie_&_Vincent_1.mat
  Sophie_&_Vincent_3: EPFL/colormat/Sophie_&_Vincent_3.mat
  Sophie_&_Vincent_on_a_Bench: EPFL/colormat/Sophie_&_Vincent_on_a_Bench.mat
  Sophie_Krios_&_Vincent: EPFL/colormat/Sophie_Krios_&_Vincent.mat
  Swans_1: EPFL/colormat/Swans_1.mat
  Trunk: EPFL/colormat/Trunk.mat
  University: EPFL/colormat/University.mat
  Vine_Wood: EPFL/colormat/Vine_Wood.mat
  Wall_Decoration: EPFL/colormat/Wall_Decoration.mat
  Wood_&_Net: EPFL/colormat/Wood_&_Net.mat
  Yan_&_Krios_1: EPFL/colormat/Yan_&_Krios_1.mat
  Yan_&_Krios_2: EPFL/colormat/Yan_&_Krios_2.mat
  Yan_&_Krios_standing: EPFL/colormat/Yan_&_Krios_standing.mat
  Zwahlen_&_Mayr: EPFL/colormat/Zwahlen_&_Mayr.mat
  bikes_1: Stanford_Archive/colormat/bikes/bikes_1.mat
  bikes_12: Stanford_Archive/colormat/bikes/bikes_12.mat
  bikes_14: Stanford_Archive/colormat/bikes/bikes_14.mat
  bikes_18: Stanford_Archive/colormat/bikes/bikes_18.mat
  bikes_19: Stanford_Archive/colormat/bikes/bikes_19.mat
  bikes_4: Stanford_Archive/colormat/bikes/bikes_4.mat
  bikes_5: Stanford_Archive/colormat/bikes/bikes_5.mat
  bikes_6: Stanford_Archive/colormat/bikes/bikes_6.mat
  bikes_7: Stanford_Archive/colormat/bikes/bikes_7.mat
  bikes_8: Stanford_Archive/colormat/bikes/bikes_8.mat
  bikes_9: Stanford_Archive/colormat/bikes/bikes_9.mat
  buildings_10: Stanford_Archive/colormat/buildings/buildings_10.mat
  buildings_11: Stanford_Archive/colormat/buildings/buildings_11.mat
  buildings_13: Stanford_Archive/colormat/buildings/buildings_13.mat
  buildings_14: Stanford_Archive/colormat/buildings/buildings_14.mat
  buildings_15: Stanford_Archive/colormat/buildings/buildings_15.mat
  buildings_17: Stanford_Archive/colormat/buildings/buildings_17.mat
  buildings_18: Stanford_Archive/colormat/buildings/buildings_18.mat
  buildings_2: Stanford_Archive/colormat/buildings/buildings_2.mat
  buildings_20: Stanford_Archive/colormat/buildings/buildings_20.mat
  buildings_22: Stanford_Archive/colormat/buildings/buildings_22.mat
  buildings_23: Stanford_Archive/colormat/buildings/buildings_23.mat
  buildings_24: Stanford_Archive/colormat/buildings/buildings_24.mat
  buildings_25: Stanford_Archive/colormat/buildings/buildings_25.mat
  buildings_26: Stanford_Archive/colormat/buildings/buildings_26.mat
  buildings_27: Stanford_Archive/colormat/buildings/buildings_27.mat
  buildings_28: Stanford_Archive/colormat/buildings/buildings_28.mat
  buildings_3: Stanford_Archive/colormat/buildings/buildings_3.mat
  buildings_30: Stanford_Archive/colormat/buildings/buildings_30.mat
  buildings_33: Stanford_Archive/colormat/buildings/buildings_33.mat
  buildings_5: Stanford_Archive/colormat/buildings/buildings_5.mat
  buildings_6: Stanford_Archive/colormat/buildings/buildings_6.mat
  buildings_8: Stanford_Archive/colormat/buildings/buildings_8.mat
  buildings_9: Stanford_Archive/colormat/buildings/buildings_9.mat
  cars_1: Stanford_Archive/colormat/cars/cars_1.mat
  cars_12: Stanford_Archive/colormat/cars/cars_12.mat
  cars_13: Stanford_Archive/colormat/cars/cars_13.mat
  cars_14: Stanford_Archive/colormat/cars/cars_14.mat
  cars_15: Stanford_Archive/colormat/cars/cars_15.mat
  cars_17: Stanford_Archive/colormat/cars/cars_17.mat
  cars_19: Stanford_Archive/colormat/cars/cars_19.mat
  cars_2: Stanford_Archive/colormat/cars/cars_2.mat
  cars_20: Stanford_Archive/colormat/cars/cars_20.mat
  cars_21: Stanford_Archive/colormat/cars/cars_21.mat
  cars_22: Stanford_Archive/colormat/cars/cars_22.mat
  cars_23: Stanford_Archive/colormat/cars/cars_23.mat
  cars_24: Stanford_Archive/colormat/cars/cars_24.mat
  cars_26: Stanford_Archive/colormat/cars/cars_26.mat
  cars_28: Stanford_Archive/colormat/cars/cars_28.mat
  cars_3: Stanford_Archive/colormat/cars/cars_3.mat
  cars_30: Stanford_Archive/colormat/cars/cars_30.mat
  cars_32: Stanford_Archive/colormat/cars/cars_32.mat
  cars_35: Stanford_Archive/colormat/cars/cars_35.mat
  cars_36: Stanford_Archive/colormat/cars/cars_36.mat
  cars_37: Stanford_Archive/colormat/cars/cars_37.mat
  cars_38: Stanford_Archive/colormat/cars/cars_38.mat
  cars_39: Stanford_Archive/colormat/cars/cars_39.mat
  cars_44: Stanford_Archive/colormat/cars/cars_44.mat
  cars_46: Stanford_Archive/colormat/cars/cars_46.mat
  cars_47: Stanford_Archive/colormat/cars/cars_47.mat
  cars_48: Stanford_Archive/colormat/cars/cars_48.mat
  cars_49: Stanford_Archive/colormat/cars/cars_49.mat
  cars_50: Stanford_Archive/colormat/cars/cars_50.mat
  cars_53: Stanford_Archive/colormat/cars/cars_53.mat
  cars_56: Stanford_Archive/colormat/cars/cars_56.mat
  cars_6: Stanford_Archive/colormat/cars/cars_6.mat
  cars_7: Stanford_Archive/colormat/cars/cars_7.mat
  cars_9: Stanford_Archive/colormat/cars/cars_9.mat
  flowers_plants_1: Stanford_Archive/colormat/flowers_plants/flowers_plants_1.mat
  flowers_plants_12: Stanford_Archive/colormat/flowers_plants/flowers_plants_12.mat
  flowers_plants_14: Stanford_Archive/colormat/flowers_plants/flowers_plants_14.mat
  flowers_plants_15: Stanford_Archive/colormat/flowers_plants/flowers_plants_15.mat
  flowers_plants_16: Stanford_Archive/colormat/flowers_plants/flowers_plants_16.mat
  flowers_plants_19: Stanford_Archive/colormat/flowers_plants/flowers_plants_19.mat
  flowers_plants_2: Stanford_Archive/colormat/flowers_plants/flowers_plants_2.mat
  flowers_plants_20: Stanford_Archive/colormat/flowers_plants/flowers_plants_20.mat
  flowers_plants_22: Stanford_Archive/colormat/flowers_plants/flowers_plants_22.mat
  flowers_plants_24: Stanford_Archive/colormat/flowers_plants/flowers_plants_24.mat
  flowers_plants_26: Stanford_Archive/colormat/flowers_plants/flowers_plants_26.mat
  flowers_plants_27: Stanford_Archive/colormat/flowers_plants/flowers_plants_27.mat
  flowers_plants_29: Stanford_Archive/colormat/flowers_plants/flowers_plants_29.mat
  flowers_plants_3: Stanford_Archive/colormat/flowers_plants/flowers_plants_3.mat
  flowers_plants_33: Stanford_Archive/colormat/flowers_plants/flowers_plants_33.mat
  flowers_plants_34: Stanford_Archive/colormat/flowers_plants/flowers_plants_34.mat
  flowers_plants_35: Stanford_Archive/colormat/flowers_plants/flowers_plants_35.mat
  flowers_plants_36: Stanford_Archive/colormat/flowers_plants/flowers_plants_36.mat
  flowers_plants_37: Stanford_Archive/colormat/flowers_plants/flowers_plants_37.mat
  flowers_plants_39: Stanford_Archive/colormat/flowers_plants/flowers_plants_39.mat
  flowers_plants_4: Stanford_Archive/colormat/flowers_plants/flowers_plants_4.mat
  flowers_plants_41: Stanford_Archive/colormat/flowers_plants/flowers_plants_41.mat
  flowers_plants_42: Stanford_Archive/colormat/flowers_plants/flowers_plants_42.mat
  flowers_plants_43: Stanford_Archive/colormat/flowers_plants/flowers_plants_43.mat
  flowers_plants_44: Stanford_Archive/colormat/flowers_plants/flowers_plants_44.mat
  flowers_plants_45: Stanford_Archive/colormat/flowers_plants/flowers_plants_45.mat
  flowers_plants_47: Stanford_Archive/colormat/flowers_plants/flowers_plants_47.mat
  flowers_plants_48: Stanford_Archive/colormat/flowers_plants/flowers_plants_48.mat
  flowers_plants_49: Stanford_Archive/colormat/flowers_plants/flowers_plants_49.mat
  flowers_plants_5: Stanford_Archive/colormat/flowers_plants/flowers_plants_5.mat
  flowers_plants_50: Stanford_Archive/colormat/flowers_plants/flowers_plants_50.mat
  flowers_plants_51: Stanford_Archive/colormat/flowers_plants/flowers_plants_51.mat
  flowers_plants_57: Stanford_Archive/colormat/flowers_plants/flowers_plants_57.mat
  flowers_plants_58: Stanford_Archive/colormat/flowers_plants/flowers_plants_58.mat
  flowers_plants_59: Stanford_Archive/colormat/flowers_plants/flowers_plants_59.mat
  flowers_plants_62: Stanford_Archive/colormat/flowers_plants/flowers_plants_62.mat
  flowers_plants_63: Stanford_Archive/colormat/flowers_plants/flowers_plants_63.mat
  flowers_plants_65: Stanford_Archive/colormat/flowers_plants/flowers_plants_65.mat
  flowers_plants_9: Stanford_Archive/colormat/flowers_plants/flowers_plants_9.mat
  fruits_vegetables_1: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_1.mat
  fruits_vegetables_10: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_10.mat
  fruits_vegetables_11: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_11.mat
  fruits_vegetables_12: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_12.mat
  fruits_vegetables_13: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_13.mat
  fruits_vegetables_18: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_18.mat
  fruits_vegetables_2: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_2.mat
  fruits_vegetables_20: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_20.mat
  fruits_vegetables_5: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_5.mat
  fruits_vegetables_6: Stanford_Archive/colormat/fruits_vegetables/fruits_vegetables_6.mat
  general_1: Stanford_Archive/colormat/general/general_1.mat
  general_10: Stanford_Archive/colormat/general/general_10.mat
  general_11: Stanford_Archive/colormat/general/general_11.mat
  general_12: Stanford_Archive/colormat/general/general_12.mat
  general_15: Stanford_Archive/colormat/general/general_15.mat
  general_16: Stanford_Archive/colormat/general/general_16.mat
  general_17: Stanford_Archive/colormat/general/general_17.mat
  general_2: Stanford_Archive/colormat/general/general_2.mat
  general_21: Stanford_Archive/colormat/general/general_21.mat
  general_22: Stanford_Archive/colormat/general/general_22.mat
  general_23: Stanford_Archive/colormat/general/general_23.mat
  general_24: Stanford_Archive/colormat/general/general_24.mat
  general_25: Stanford_Archive/colormat/general/general_25.mat
  general_26: Stanford_Archive/colormat/general/general_26.mat
  general_27: Stanford_Archive/colormat/general/general_27.mat
  general_28: Stanford_Archive/colormat/general/general_28.mat
  general_29: Stanford_Archive/colormat/general/general_29.mat
  general_3: Stanford_Archive/colormat/general/general_3.mat
  general_30: Stanford_Archive/colormat/general/general_30.mat
  general_31: Stanford_Archive/colormat/general/general_31.mat
  general_32: Stanford_Archive/colormat/general/general_32.mat
  general_33: Stanford_Archive/colormat/general/general_33.mat
  general_34: Stanford_Archive/colormat/general/general_34.mat
  general_36: Stanford_Archive/colormat/general/general_36.mat
  general_37: Stanford_Archive/colormat/general/general_37.mat
  general_38: Stanford_Archive/colormat/general/general_38.mat
  general_39: Stanford_Archive/colormat/general/general_39.mat
  general_41: Stanford_Archive/colormat/general/general_41.mat
  general_42: Stanford_Archive/colormat/general/general_42.mat
  general_44: Stanford_Archive/colormat/general/general_44.mat
  general_45: Stanford_Archive/colormat/general/general_45.mat
  general_46: Stanford_Archive/colormat/general/general_46.mat
  general_47: Stanford_Archive/colormat/general/general_47.mat
  general_48: Stanford_Archive/colormat/general/general_48.mat
  general_5: Stanford_Archive/colormat/general/general_5.mat
  general_50: Stanford_Archive/colormat/general/general_50.mat
  general_54: Stanford_Archive/colormat/general/general_54.mat
  general_56: Stanford_Archive/colormat/general/general_56.mat
  general_6: Stanford_Archive/colormat/general/general_6.mat
  people_1: Stanford_Archive/colormat/people/people_1.mat
  people_10: Stanford_Archive/colormat/people/people_10.mat
  people_12: Stanford_Archive/colormat/people/people_12.mat
  people_14: Stanford_Archive/colormat/people/people_14.mat
  people_16: Stanford_Archive/colormat/people/people_16.mat
  people_2: Stanford_Archive/colormat/people/people_2.mat
  people_5: Stanford_Archive/colormat/people/people_5.mat
  people_6: Stanford_Archive/colormat/people/people_6.mat
  people_8: Stanford_Archive/colormat/people/people_8.mat
  people_9: Stanford_Archive/colormat/people/people_9.mat
synthesis:
  antinous: HCI_new/colormat/antinous.mat
  backgammon: HCI_new/colormat/backgammon.mat
  bedroom: HCI_new/colormat/bedroom.mat
  boxes: HCI_new/colormat/boxes.mat
  cotton: HCI_new/colormat/cotton.mat
  cube: HCI_old/colormat/cube.mat
  dishes: HCI_new/colormat/dishes.mat
  herbs: HCI_new/colormat/herbs.mat
  horses: HCI_old/colormat/horses.mat
  medieval: HCI_old/colormat/medieval.mat
  medieval2: HCI_new/colormat/medieval2.mat
  museum: HCI_new/colormat/museum.mat
  origami: HCI_new/colormat/origami.mat
  pillows: HCI_new/colormat/pillows.mat
  platonic: HCI_new/colormat/platonic.mat
  pyramide: HCI_old/colormat/pyramide.mat
  pyramids: HCI_new/colormat/pyramids.mat
  stillLife: HCI_old/colormat/stillLife.mat
  stripes: HCI_new/colormat/stripes.mat
  table: HCI_new/colormat/table.mat
  tomb: HCI_new/colormat/tomb.mat
  tower: HCI_new/colormat/tower.mat
  town: HCI_new/colormat/town.mat
  vinyl: HCI_new/colormat/vinyl.mat
  kitchen: HCI_new/colormat/kitchen.mat
